# Task 2
print("Task 2:")
print(3+4)
print(3-4)
print(3*4)
print(3%4)
print(3/4)
print(3**4)
print(3//4)
print("")

# Task 3
print("Task 3:")
print("Name: ", "Muhammad Abdullah")
print("Father Name: ", "Zahid Mehmood")
print("Country: ", "Pakistan")
print("I am enjoying 30 days of python")
print("")

# Task 4
print("Task 4:")
print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4-4j))
print(type(['Abdullah','Python','Pakistan']))
print(type("Abdullah"))
print(type("Zahid"))
print(type("Pakistan"))
print("")
